// Copyright (c) 2024-2026 Ronan LE MEILLAT
// License: AGPL-3.0-or-later

import type { Topic } from '../../knowledge/base.js';
import type { HeaderMeta, TopicChecksumResult } from './types.js';

/**
 * Compute a SHA-256 hash of a string using Web Crypto.
 *
 * This helper is used to fingerprint source content and manual facts.
 *
 * @param value - Input text to hash.
 * @returns Hex-encoded SHA-256 digest.
 */
export async function hashString(value: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(value);
  const globalCrypto = (globalThis as any).crypto;
  const subtle = globalCrypto?.subtle;

  if (!subtle || typeof subtle.digest !== 'function') {
    throw new Error('No Web Crypto API available to compute SHA-256 hash.');
  }

  const digest = await subtle.digest('SHA-256', data);
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Compute checksum metadata for a topic based on its sources and manual facts.
 *
 * This function reads all source files, hashes their content, and returns
 * stable signatures used to detect when a topic needs regeneration.
 *
 * @param topic - Topic metadata object.
 * @param readSource - Reader function returning file content.
 * @returns Checksum data for the topic.
 */
export async function computeTopicChecksums(
  topic: Topic,
  readSource: (relativePath: string) => string | Promise<string>,
): Promise<TopicChecksumResult> {
  const manualFactsText = (topic.manualFacts ?? []).join('\n');
  const sourceFileHashes: Record<string, string> = {};
  const sourceBlocks: string[] = [];

  for (const srcPath of topic.sources) {
    const content = await Promise.resolve(readSource(srcPath));
    const hash = await hashString(`${srcPath}\n${content}`);
    sourceFileHashes[srcPath] = hash;
    sourceBlocks.push(`${srcPath}\n${content}`);
  }

  return {
    manualFactsChecksum: await hashString(manualFactsText),
    sourcesChecksum: await hashString(sourceBlocks.join('\n---\n')),
    sourceFileHashes,
  };
}

/**
 * Parse embedded checksum values from generated topic markdown.
 *
 * The generator includes source and manual facts checksums in the file header.
 * This helper extracts those values for comparison.
 *
 * @param content - Raw markdown text.
 * @returns Parsed checksum values.
 */
export function parseHeaderChecksums(content: string): {
  manualFactsChecksum?: string;
  sourcesChecksum?: string;
} {
  const manualFactsMatch = content.match(/manual_facts_checksum:\s*([0-9a-f]{64})/);
  const sourcesMatch = content.match(/sources_checksum:\s*([0-9a-f]{64})/);
  return {
    manualFactsChecksum: manualFactsMatch?.[1],
    sourcesChecksum: sourcesMatch?.[1],
  };
}

/**
 * Build the generated markdown header for a topic file.
 *
 * The header contains metadata such as model, token usage, checksums,
 * and per-file source hashes.
 *
 * @param description - Short description of the generated topic.
 * @param meta - Optional metadata fields to include.
 * @returns A markdown comment block.
 */
export function buildHeader(description: string, meta?: HeaderMeta): string {
  const headerLines = [
    '<!--',
    '  AUTO-GENERATED by apps/mcp/src/lib/generate-knowledge-modules/generate.ts',
    '  Do not edit manually. Run the script to regenerate.',
    '  To add or modify topics, edit files in apps/mcp/src/knowledge/topics/',
    `  description:  ${description}`,
  ];

  if (meta?.model) headerLines.push(`  model:        ${meta.model}`);
  if (meta?.tokensIn !== undefined) headerLines.push(`  tokens_in:    ${meta.tokensIn}`);
  if (meta?.tokensOut !== undefined) headerLines.push(`  tokens_out:   ${meta.tokensOut}`);
  if (meta?.apiEndpoint) headerLines.push(`  api_endpoint: ${meta.apiEndpoint}`);
  if (meta?.manualFactsChecksum) headerLines.push(`  manual_facts_checksum: ${meta.manualFactsChecksum}`);
  if (meta?.sourcesChecksum) headerLines.push(`  sources_checksum: ${meta.sourcesChecksum}`);
  if (meta?.sourceFileHashes) {
    headerLines.push('  source_file_hashes:');
    for (const [path, hash] of Object.entries(meta.sourceFileHashes)) {
      headerLines.push(`    ${path}: ${hash}`);
    }
  }

  headerLines.push('-->\n');
  return headerLines.join('\n');
}
