/**
 * Copyright (c) 2026 Ronan LE MEILLAT - SCTG Development
 * License: AGPL-3.0-or-later
 */
import type { Topic } from '../base.js';
import { BASE_SYSTEM, appendFacts } from '../base.js';

const topic: Topic = {
  name: 'mcp-maintenance-guide',
  description: "Call this when you need to maintain or extend the Fufuni MCP knowledge base.",
  tags: ["mcp","knowledge","maintenance","documentation"],
  sources: [
    'apps/mcp/src/knowledge/base.ts',
    'apps/mcp/src/tools.ts',
    'apps/mcp/src/index.ts',
    'apps/mcp/src/stdio.ts',
    'apps/mcp/wrangler.jsonc',
    'apps/mcp/package.json',
    'package.json',
  ],
  systemPrompt: BASE_SYSTEM,
  manualFacts: [
    // ── Architecture ────────────────────────────────────────────────────────
    'The MCP server lives entirely in apps/mcp/. It is a Cloudflare Worker + Durable Object (class FufuniMCP) that exposes knowledge-base tools to AI assistants via HTTP SSE (/mcp) or stdio.',
    'Tool registration happens in apps/mcp/src/tools.ts → registerFufuniTools(). Every tool response is wrapped in withKvCache() (apps/mcp/src/lib/kv-cache.ts) to avoid redundant decryption and BM25 searches.',
    'The knowledge base is a static bundle compiled at build time: apps/mcp/src/knowledge.ts (Markdown content), apps/mcp/src/search/chunks.ts (BM25 chunks), apps/mcp/src/search/bm25-index.ts (index). NEVER edit those files directly — they are auto-generated by scripts/gen-knowledge.ts.',
    'apps/mcp/src/manifest.ts is also auto-generated. It holds the topic metadata (name, description, tags, commit hash) consumed at runtime by list_topics and get_manifest.',

    // ── Topic authoring ─────────────────────────────────────────────────────
    'Topic files live in apps/mcp/src/knowledge/topics/. Each file exports a default Topic object (type from base.ts). The generator auto-discovers all *.ts files in that directory alphabetically.',
    'Required Topic fields: name (string, matches filename stem), description (≤ 200 chars, auto-generated by LLM then patched by patchTopicTs()), tags (string[], closed vocab, auto-patched), sources (paths relative to repo root), systemPrompt (always BASE_SYSTEM), buildPrompt (function receiving concatenated source text).',
    'Optional Topic fields: manualFacts (string[] — curated facts the LLM must treat as absolute truth, higher priority than source code), staticAppend (verbatim Markdown appended after AI output), maxSourceChars (override per-source character budget).',
    'Copyright header required in every new topic file: "Copyright (c) 2026 Ronan LE MEILLAT - SCTG Development / License: AGPL-3.0-or-later".',
    'The description and tags fields are auto-populated by the LLM on first generation (BASE_SYSTEM instructs the LLM to emit <!--mcp-description: ...--> and <!--mcp-tags: [...]-->). patchTopicTs() rewrites those fields in the .ts source after each successful generation. You do not need to fill them manually.',

    // ── Mandatory checklist when Fufuni evolves ──────────────────────────────
    'CHECKLIST — When you add a new feature to Fufuni (new route, new migration, new frontend component), you MUST: (1) check if an existing topic covers it → add the new source file to its sources[] array; (2) if no existing topic covers it → create a new topic file; (3) add any non-obvious facts (security rules, naming conventions, gotchas) to manualFacts[]; (4) run npm run mcp:auto:flash (or mcp:auto:mistral) to regenerate only the changed topics.',
    'CHECKLIST — When you rename or move a source file: update all sources[] arrays in every topic that references that path. The generator will fail silently (source missing) if a path is wrong.',
    'CHECKLIST — When you change a naming convention or add a global constraint: add it to the manualFacts[] of the most relevant topic AND to apps/mcp/src/knowledge/base.ts BASE_SYSTEM if it applies to all topics.',
    'CHECKLIST — When you add a new DB migration: update the migrations-reference topic sources[] to include the new SQL file. Run mcp:auto:flash after.',
    'CHECKLIST — When you add an Auth0 action, rule, or flow change: update auth-patterns.ts and/or jwt-user-metadata-patterns.ts manualFacts[].',
    'You can manually override description or tags before running generation. The LLM will re-patch them on the next --force regeneration, so manual overrides are only stable when using --auto-refresh (which skips unchanged topics).',

    // ── Regeneration commands ────────────────────────────────────────────────
    'npm run mcp:auto:flash — Uses Gemini free tier (round-robin across 21 keys in ai.json.enc). Flags: --auto-refresh (only regenerates topics whose source+manualFacts checksum changed), --max-token-override=30000, --no-model-fallback, --provider=gemini. Then runs gen-knowledge. Requires CRYPTOKEN env var for decrypting ai.json.enc.',
    'npm run mcp:auto:mistral — Same as flash but uses Mistral free tier (6 keys). Flags: --max-token-override=99000 (larger context window). Prefer for topics with many large source files.',
    'npm run mcp:generate — Dry-run-safe: skips topics that already have valid .md output. Reads AI_MODEL, AI_API_KEY, AI_API_URL from env (not ai.json.enc). Useful for CI or single-topic regeneration.',
    'npm run mcp:generate:force — Forces regeneration of ALL topics regardless of existing .md files. Use after a major BASE_SYSTEM change or a global refactor.',
    'cd apps/mcp && npm run gen-knowledge — Reads all .md files in mcp/ (repo root) and rebuilds knowledge.ts, bm25-index.ts, chunks.ts, manifest.ts. Run this after any manual edit to a .md file or after generate finishes.',
    'Single-topic regeneration: npm run mcp:generate -- --topic=<name> --force --provider=gemini (with CRYPTOKEN set). Fastest for iterating on one topic.',

    // ── VS Code installation ─────────────────────────────────────────────────
    'VS Code installation — HTTP mode (remote, production): create .vscode/mcp.json with: { "servers": { "fufuni": { "type": "http", "url": "https://fufuni-mcp.fufuni.workers.dev/mcp" } } }. The file is in .gitignore and stored encrypted in _sensitive_datas.',
    'VS Code installation — stdio mode (local dev, no network): create .vscode/mcp.json with: { "servers": { "fufuni": { "type": "stdio", "command": "npm", "args": ["--prefix", "apps/mcp", "run", "stdio"] } } }. The stdio script sources .env automatically (includes CRYPTOKEN).',
    'VS Code installation — local HTTP mode (wrangler dev): run "npm run dev" inside apps/mcp/ to start the Worker on port 8788, then use url: "http://localhost:8788/mcp" in mcp.json.',
    'Claude Desktop installation — add to ~/Library/Application Support/Claude/claude_desktop_config.json: { "mcpServers": { "fufuni": { "command": "npx", "args": ["mcp-remote", "https://fufuni-mcp.fufuni.workers.dev/mcp"] } } }.',
    'After changing mcp.json or restarting the Worker, run "MCP: Restart Server" in the VS Code command palette to reconnect Copilot.',

    // ── Deployment ──────────────────────────────────────────────────────────
    'Deployment: npm run deploy inside apps/mcp/ (runs build:sources then wrangler deploy). The MANIFEST_COMMIT value is baked in at build time and invalidates all KV cache entries automatically on every redeploy.',
    'KV cache binding is KV_CACHE in wrangler.jsonc. Cache TTL: 3600s for retrieve_knowledge and get_manifest, 86400s for static tools (list_topics, get_topic, etc.). All keys include MANIFEST_COMMIT so redeploying always starts with a cold cache.',
  ],
  buildPrompt: (src) => appendFacts(`
Below are the relevant source files for the Fufuni MCP server:

${src}

Task: Write a "MCP Maintenance Guide" for the sole developer of the Fufuni project.

The guide must cover exactly these four sections:

## Development Architecture
Describe the runtime structure of the MCP server:
- Cloudflare Worker + Durable Object (FufuniMCP), HTTP SSE vs stdio transport
- registerFufuniTools() in tools.ts: how tools are registered, how withKvCache() wraps each handler
- The auto-generated files (knowledge.ts, bm25-index.ts, chunks.ts, manifest.ts) and why they must never be edited manually
- The KV_CACHE binding and MANIFEST_COMMIT-based invalidation strategy

## Authoring and Maintaining Topics
Explain the Topic interface with all fields (name, description, tags, sources, systemPrompt, buildPrompt, manualFacts, staticAppend, maxSourceChars) and their roles.
Then give the complete mandatory checklist the developer must go through each time Fufuni gains a new feature, route, migration, or convention. For each item in the checklist, explain WHICH field to update and WHY.
Show a complete minimal topic file as a TypeScript code example.

## VS Code Installation
Show all three installation modes with their complete .vscode/mcp.json snippets:
1. HTTP mode — remote production Worker
2. stdio mode — local npm run stdio subprocess
3. Local HTTP mode — wrangler dev on port 8788
Also show the Claude Desktop config.
Mention: .vscode/mcp.json is in .gitignore; use "MCP: Restart Server" from the VS Code command palette after changes.

## Regeneration Workflow
Document every regeneration command in order of typical use:
- mcp:auto:flash (Gemini, auto-refresh, requires CRYPTOKEN)
- mcp:auto:mistral (Mistral, larger context window)
- mcp:generate (direct AI env vars, no encrypted config)
- mcp:generate:force (full rebuild)
- Single-topic: --topic=<name> --force
- gen-knowledge (final step, always)
For each command, state: which provider, when to use it, required env vars, what it writes to disk.
`, topic.manualFacts),
};

export default topic;
