-- Migration 031: add thumbnail_url column to categories
-- Used for small WebP thumbnails (≤ 300 px, base64 inline or R2 URL)
-- Auto-generated by the admin client when uploading a category image
ALTER TABLE categories ADD COLUMN thumbnail_url TEXT;
