// Copyright (c) 2024-2026 Ronan LE MEILLAT
// License: AGPL-3.0-or-later
//
// AUTO-GENERATED by apps/mcp/scripts/build-sources.ts
// Do not edit manually — run: npm run build:sources
// Requires openapi.json at repo root (run: cd apps/merchant && npm run gen:openapi)

import type { RouteInfo } from "../lib/route-parser.js";

/**
 * All API routes extracted from openapi.json (generated by OpenAPIHono.doc31 at runtime).
 * Updated at build time — reflects the full route surface, not a regex approximation.
 */
export const ROUTES: RouteInfo[] = [
  {
    "method": "GET",
    "path": "/.well-known/ucp",
    "summary": "UCP discovery profile",
    "description": "Returns the UCP capabilities, services, and payment handlers for this merchant.",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "GET",
    "path": "/ucp/v1/categories",
    "summary": "Browse categories",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "POST",
    "path": "/ucp/v1/checkout-sessions",
    "summary": "Create checkout session",
    "description": "Creates a UCP checkout session from a list of line items.",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "DELETE",
    "path": "/ucp/v1/checkout-sessions/{id}",
    "summary": "Cancel checkout session",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "GET",
    "path": "/ucp/v1/checkout-sessions/{id}",
    "summary": "Get checkout session",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "PATCH",
    "path": "/ucp/v1/checkout-sessions/{id}",
    "summary": "Partial update of checkout session",
    "description": "Updates buyer info and/or item quantities without full re-resolution. Taxes are recalculated if quantities change.",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "PUT",
    "path": "/ucp/v1/checkout-sessions/{id}",
    "summary": "Update checkout session",
    "description": "Full replacement of line items, buyer, and currency with price re-resolution.",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "POST",
    "path": "/ucp/v1/checkout-sessions/{id}/complete",
    "summary": "Complete checkout session",
    "description": "Initiates payment via the specified handler. Returns requires_escalation with a redirect URL if Stripe is used, or a graceful fallback if no handler is available.",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "POST",
    "path": "/ucp/v1/checkout-sessions/{id}/estimate-shipping",
    "summary": "Estimate shipping options",
    "description": "Returns available shipping rates for the given country code.",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "GET",
    "path": "/ucp/v1/products",
    "summary": "Browse products",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "GET",
    "path": "/ucp/v1/products/{id}",
    "summary": "Get product",
    "tags": [
      "UCP"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/__auth0/autopermissions",
    "summary": "Auto-assign configured permissions to caller",
    "description": "Reads `AUTH0_AUTOMATIC_PERMISSIONS` and adds any missing values to the current Auth0 user via the Management API.",
    "tags": [
      "Auth0"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/__auth0/get/:user",
    "summary": "Debug request info (admin:store)",
    "description": "Returns detailed session and request info. Required permission: admin:store",
    "tags": [
      "Auth0"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/__auth0/token",
    "summary": "Retrieve an Auth0 Management API token",
    "description": "Calls Auth0 using the client_credentials grant, caches the result and returns the raw access token (for use by admin UIs).",
    "tags": [
      "Auth0"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/admin/order-email-settings",
    "summary": "List all order email notification settings",
    "tags": [
      "Order Email Settings"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/admin/order-email-settings/:event",
    "summary": "Delete email notification settings for an order event (reverts to global fallback)",
    "tags": [
      "Order Email Settings"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/admin/order-email-settings/:event",
    "summary": "Get e-mail setting for a specific order event",
    "tags": [
      "Order Email Settings"
    ]
  },
  {
    "method": "PUT",
    "path": "/v1/admin/order-email-settings/:event",
    "summary": "Create or update email notification settings for an order event",
    "tags": [
      "Order Email Settings"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ai/config",
    "summary": "Upload encrypted AI configuration to Cloudflare KV",
    "description": "Stores the raw ai.json.enc payload under the KV key \"ai:config\" so the worker can decrypt it at runtime.",
    "tags": [
      "AI"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/ai/parameters",
    "summary": "Retrieve AI configuration for the client",
    "description": "Returns the API key, model and base URL for the AI provider. Requires ai:api permission. Selects a non-expired key randomly from the highest-priority model. Optionally filter by provider using the ?provider=<key> query parameter.",
    "tags": [
      "AI"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/analytics/cache-stats",
    "summary": "Get KV and CDN cache performance metrics (admin)",
    "tags": [
      "Analytics"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/analytics/dashboard",
    "summary": "Get store dashboard stats (admin)",
    "tags": [
      "Analytics"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/carts",
    "summary": "Create a new cart",
    "tags": [
      "Checkout"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/carts/{cartId}",
    "summary": "Get cart by ID",
    "tags": [
      "Checkout"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/carts/{cartId}/apply-discount",
    "summary": "Apply discount code to cart",
    "tags": [
      "Checkout"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/carts/{cartId}/available-shipping-rates",
    "summary": "List applicable shipping rates for this cart",
    "description": "Returns shipping rates compatible with the cart's region, destination country and total weight. Requires a shipping address to be set on the cart first.",
    "tags": [
      "Checkout"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/carts/{cartId}/checkout",
    "summary": "Initiate Stripe checkout",
    "description": "Creates a Stripe checkout session and returns the URL",
    "tags": [
      "Checkout"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/carts/{cartId}/discount",
    "summary": "Remove discount from cart",
    "tags": [
      "Checkout"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/carts/{cartId}/items",
    "summary": "Add items to cart",
    "description": "Replaces existing cart items with the provided items",
    "tags": [
      "Checkout"
    ]
  },
  {
    "method": "PUT",
    "path": "/v1/carts/{cartId}/shipping-address",
    "summary": "Set shipping address on cart",
    "description": "Stores the customer delivery address on the cart. Required before selecting a shipping rate.",
    "tags": [
      "Checkout"
    ]
  },
  {
    "method": "PUT",
    "path": "/v1/carts/{cartId}/shipping-rate",
    "summary": "Select a shipping rate for the cart",
    "description": "Stores the chosen shipping rate and updates shipping_cents in the cart totals.",
    "tags": [
      "Checkout"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/categories",
    "summary": "List all active categories",
    "description": "Returns flat list of active categories, ready for building tree structure client-side",
    "tags": [
      "Categories"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/categories",
    "summary": "Create a category (admin)",
    "tags": [
      "Categories"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/categories/:handle",
    "summary": "Get a category by handle",
    "tags": [
      "Categories"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/categories/:handle/products",
    "summary": "List products in a category by handle",
    "tags": [
      "Categories"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/categories/:id",
    "summary": "Delete a category (admin)",
    "tags": [
      "Categories"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/categories/:id",
    "summary": "Update a category (admin)",
    "tags": [
      "Categories"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/categories/:id/products",
    "summary": "Assign products to a category (admin)",
    "tags": [
      "Categories"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/categories/:id/products/:productId",
    "summary": "Remove a product from a category (admin)",
    "tags": [
      "Categories"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/customers",
    "summary": "List customers",
    "description": "List customers with pagination and optional search",
    "tags": [
      "Customers"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/customers/{id}",
    "summary": "Get customer by ID",
    "description": "Returns customer details with addresses",
    "tags": [
      "Customers"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/customers/{id}",
    "summary": "Update customer",
    "tags": [
      "Customers"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/customers/{id}/addresses",
    "summary": "Add address to customer",
    "tags": [
      "Customers"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/customers/{id}/addresses/{addressId}",
    "summary": "Delete customer address",
    "tags": [
      "Customers"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/customers/{id}/orders",
    "summary": "Get customer order history",
    "tags": [
      "Customers"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/discounts",
    "summary": "List all discounts",
    "tags": [
      "Discounts"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/discounts",
    "summary": "Create a discount",
    "tags": [
      "Discounts"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/discounts/{id}",
    "summary": "Deactivate a discount",
    "tags": [
      "Discounts"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/discounts/{id}",
    "summary": "Get discount by ID",
    "tags": [
      "Discounts"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/discounts/{id}",
    "summary": "Update a discount",
    "tags": [
      "Discounts"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/images",
    "summary": "Upload an image",
    "tags": [
      "Images"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/images/{key}",
    "summary": "Delete an image",
    "tags": [
      "Images"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/images/{key}",
    "summary": "Get an image",
    "tags": [
      "Images"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/images/{key}/cache",
    "summary": "Purge a single image from CDN edge cache",
    "description": "Removes the CDN edge cache entry for one image without deleting it from R2 storage.",
    "tags": [
      "Images"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/images/cache/all",
    "summary": "Purge all images from CDN edge cache",
    "description": "Iterates all R2 image keys and removes every CDN cache entry. Does not delete images from storage.",
    "tags": [
      "Images"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/inventory",
    "summary": "List inventory levels",
    "description": "List all inventory levels with pagination, or get a single SKU by query param",
    "tags": [
      "Inventory"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/inventory/{sku}/adjust",
    "summary": "Adjust inventory level",
    "description": "Add or subtract inventory for a SKU with a reason",
    "tags": [
      "Inventory"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/inventory/{sku}/regional",
    "summary": "Get regional inventory",
    "description": "Get aggregated inventory for a SKU across all warehouses in a region",
    "tags": [
      "Inventory - Warehouse"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/inventory/{sku}/warehouse-adjust",
    "summary": "Adjust warehouse inventory level",
    "description": "Add or subtract inventory for a SKU at a specific warehouse",
    "tags": [
      "Inventory - Warehouse"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/inventory/{sku}/warehouse-delete",
    "summary": "Delete warehouse inventory",
    "description": "Remove a SKU from a warehouse (only when on_hand is 0)",
    "tags": [
      "Inventory - Warehouse"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/inventory/warehouse",
    "summary": "List warehouse inventory levels",
    "description": "List inventory levels across warehouses with optional filters",
    "tags": [
      "Inventory - Warehouse"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/mails/send",
    "summary": "Send a test email via Mailgun",
    "tags": [
      "Mail"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/addresses",
    "summary": "List my saved addresses",
    "description": "Returns all saved delivery addresses for the authenticated customer.",
    "tags": [
      "Customer Portal"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/me/addresses",
    "summary": "Add a new address",
    "description": "Creates a new delivery address for the authenticated customer.",
    "tags": [
      "Customer Portal"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/me/addresses/:id",
    "summary": "Delete an address",
    "description": "Deletes a saved delivery address.",
    "tags": [
      "Customer Portal"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/orders",
    "summary": "List my orders",
    "description": "Returns the order history of the authenticated customer, sorted by most recent.",
    "tags": [
      "Customer Portal"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/orders/:number",
    "summary": "Get order by number",
    "description": "Returns the details of a specific order by order number.",
    "tags": [
      "Customer Portal"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/preferences",
    "summary": "Get my preferences",
    "description": "Returns the customer preferences stored in Auth0 user_metadata.",
    "tags": [
      "Customer Portal"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/me/preferences",
    "summary": "Update my preferences",
    "description": "Updates customer preferences (stored in Auth0 user_metadata).",
    "tags": [
      "Customer Portal"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/profile",
    "summary": "Get my profile",
    "description": "Returns the profile of the currently authenticated customer.",
    "tags": [
      "Customer Portal"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/me/profile",
    "summary": "Update my profile",
    "description": "Updates name, phone, locale and marketing preferences for the authenticated customer.",
    "tags": [
      "Customer Portal"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/saved-carts",
    "summary": "List saved carts",
    "description": "Returns all saved carts associated with the authenticated user.",
    "tags": [
      "Saved Carts"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/me/saved-carts",
    "summary": "Save a cart",
    "description": "Associates the current cart with the authenticated user account.",
    "tags": [
      "Saved Carts"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/me/saved-carts/:cartId",
    "summary": "Delete a saved cart",
    "description": "Removes the association between the user and a saved cart (by cartId).",
    "tags": [
      "Saved Carts"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/wishlist",
    "summary": "Get user wishlist",
    "description": "Returns the authenticated user's list of favorited product IDs.",
    "tags": [
      "User Preferences"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/me/wishlist",
    "summary": "Add product to wishlist",
    "description": "Adds a product ID to the user's wishlist stored in Auth0 user_metadata.",
    "tags": [
      "User Preferences"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/me/wishlist/:productId",
    "summary": "Remove product from wishlist",
    "description": "Removes a product ID from the user's wishlist.",
    "tags": [
      "User Preferences"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/orders",
    "summary": "List orders",
    "description": "List orders with pagination and optional filters by status and email",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/orders/{orderId}",
    "summary": "Get order by ID",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/orders/{orderId}",
    "summary": "Update order status/tracking",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/orders/{orderId}/refund",
    "summary": "Refund an order",
    "description": "Full or partial refund via Stripe. Stores reason and notes for audit trail.",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/orders/{orderId}/refunds",
    "summary": "List refunds for an order",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/orders/{orderId}/regenerate-tracking-link",
    "summary": "Regenerate the order tracking link and send a new confirmation email",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/orders/{orderId}/resend-confirmation",
    "summary": "Resend order confirmation email",
    "description": "Send the order confirmation email with a tracking link. This will also (re)generate a view token if missing.",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/orders/{orderId}/status",
    "summary": "Get order status via signed token (public)",
    "description": "Retrieve order details using only the signed JWT token. No authentication needed.",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/orders/lookup",
    "summary": "Look up order by Stripe session ID (public)",
    "description": "Retrieve order details using only the Stripe checkout session ID. No authentication needed.",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/orders/test",
    "summary": "Create test order",
    "description": "Creates an order without Stripe payment (for testing)",
    "tags": [
      "Orders"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/products",
    "summary": "List products",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/products",
    "summary": "Create product",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/products/{id}",
    "summary": "Delete product",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/products/{id}",
    "summary": "Get product by ID",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/products/{id}",
    "summary": "Update product",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/products/{id}/variants",
    "summary": "Add variant to product",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/products/{id}/variants/{variantId}",
    "summary": "Delete variant",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/products/{id}/variants/{variantId}",
    "summary": "Update variant",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/products/{id}/variants/{variantId}/prices",
    "summary": "List prices for a variant by currency",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/products/{id}/variants/{variantId}/prices",
    "summary": "Set price for a variant in a specific currency",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/products/{id}/variants/{variantId}/prices/{currencyId}",
    "summary": "Remove price for a specific currency",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/products/{productId}/reviews",
    "summary": "List approved reviews for a product",
    "tags": [
      "Reviews"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/products/{productId}/reviews",
    "summary": "Submit a product review (requires customer JWT)",
    "tags": [
      "Reviews"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/products/{productId}/reviews/eligibility",
    "summary": "Check if the current customer can review this product",
    "tags": [
      "Reviews"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/products/{productId}/reviews/guest",
    "summary": "Submit a product review as a guest via signed order token",
    "tags": [
      "Reviews"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/products/pricing-audit",
    "summary": "List active variants missing a price for a given currency",
    "description": "Returns all active variants in active products that have no entry in variant_prices for the specified currency. Useful when using strict pricing (Option A).",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/products/search",
    "summary": "Search products by term (fuzzy)",
    "tags": [
      "Products"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions",
    "summary": "List all regions",
    "description": "Get a paginated list of regions",
    "tags": [
      "Regions"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions",
    "summary": "Create a new region",
    "tags": [
      "Regions"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/regions/{id}",
    "summary": "Delete a region",
    "tags": [
      "Regions"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/{id}",
    "summary": "Get a region",
    "tags": [
      "Regions"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/regions/{id}",
    "summary": "Update a region",
    "tags": [
      "Regions"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/{id}/countries",
    "summary": "Add a country to a region",
    "tags": [
      "Regions - Associations"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/{id}/shipping-rates",
    "summary": "Add a shipping rate to a region",
    "tags": [
      "Regions - Associations"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/{id}/warehouses",
    "summary": "Add a warehouse to a region",
    "tags": [
      "Regions - Associations"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/countries",
    "summary": "List all countries",
    "description": "Get a paginated list of countries",
    "tags": [
      "Regions - Countries"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/countries",
    "summary": "Create a new country",
    "tags": [
      "Regions - Countries"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/regions/countries/{id}",
    "summary": "Delete a country",
    "tags": [
      "Regions - Countries"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/countries/{id}",
    "summary": "Get a country",
    "tags": [
      "Regions - Countries"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/regions/countries/{id}",
    "summary": "Update a country",
    "tags": [
      "Regions - Countries"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/countries/batch",
    "summary": "List all countries without pagination",
    "description": "Get all countries as a simple array (for bulk operations)",
    "tags": [
      "Regions - Countries"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/countries/batch",
    "summary": "Create multiple countries in one request",
    "description": "Batch create countries for better performance",
    "tags": [
      "Regions - Countries"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/currencies",
    "summary": "List all currencies",
    "description": "Get a paginated list of currencies",
    "tags": [
      "Regions - Currencies"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/currencies",
    "summary": "Create a new currency",
    "tags": [
      "Regions - Currencies"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/regions/currencies/{id}",
    "summary": "Delete a currency",
    "tags": [
      "Regions - Currencies"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/currencies/{id}",
    "summary": "Get a currency",
    "tags": [
      "Regions - Currencies"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/regions/currencies/{id}",
    "summary": "Update a currency",
    "tags": [
      "Regions - Currencies"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/shipping-classes",
    "summary": "List all shipping classes",
    "tags": [
      "Regions - Shipping Classes"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/shipping-classes",
    "summary": "Create a shipping class",
    "tags": [
      "Regions - Shipping Classes"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/regions/shipping-classes/{id}",
    "summary": "Delete a shipping class",
    "tags": [
      "Regions - Shipping Classes"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/shipping-classes/{id}",
    "summary": "Get a shipping class",
    "tags": [
      "Regions - Shipping Classes"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/regions/shipping-classes/{id}",
    "summary": "Update a shipping class",
    "tags": [
      "Regions - Shipping Classes"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/shipping-rates",
    "summary": "List all shipping rates",
    "description": "Get a paginated list of shipping rates",
    "tags": [
      "Regions - Shipping Rates"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/shipping-rates",
    "summary": "Create a new shipping rate",
    "tags": [
      "Regions - Shipping Rates"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/regions/shipping-rates/{id}",
    "summary": "Delete a shipping rate",
    "tags": [
      "Regions - Shipping Rates"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/shipping-rates/{id}",
    "summary": "Get a shipping rate",
    "tags": [
      "Regions - Shipping Rates"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/regions/shipping-rates/{id}",
    "summary": "Update a shipping rate",
    "tags": [
      "Regions - Shipping Rates"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/shipping-rates/{id}/prices",
    "summary": "List prices for a shipping rate",
    "tags": [
      "Regions - Shipping Rates"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/shipping-rates/{id}/prices",
    "summary": "Add a price to a shipping rate",
    "tags": [
      "Regions - Shipping Rates"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/warehouses",
    "summary": "List all warehouses",
    "description": "Get a paginated list of warehouses ordered by priority",
    "tags": [
      "Regions - Warehouses"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/regions/warehouses",
    "summary": "Create a new warehouse",
    "tags": [
      "Regions - Warehouses"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/regions/warehouses/{id}",
    "summary": "Delete a warehouse",
    "tags": [
      "Regions - Warehouses"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/regions/warehouses/{id}",
    "summary": "Get a warehouse",
    "tags": [
      "Regions - Warehouses"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/regions/warehouses/{id}",
    "summary": "Update a warehouse",
    "tags": [
      "Regions - Warehouses"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/reviews/:reviewId/status",
    "summary": "Approve or reject a review (admin)",
    "tags": [
      "Reviews"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/reviews/admin",
    "summary": "List all reviews across all products (admin)",
    "tags": [
      "Reviews"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/reviews/admin/seed",
    "summary": "Insert a seeded review directly (admin, bypasses purchase check)",
    "tags": [
      "Reviews"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/setup/config",
    "summary": "Get config values",
    "description": "Return all key/value pairs stored in the config table.",
    "tags": [
      "Setup"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/setup/init",
    "summary": "Initialize API keys",
    "description": "Create initial API keys (only works if no keys exist)",
    "tags": [
      "Setup"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/setup/migrations/clean",
    "summary": "Clean migrations table",
    "description": "Deletes all rows from the migrations table.",
    "tags": [
      "Setup"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/setup/migrations/list",
    "summary": "List applied migrations",
    "description": "Returns rows from the migrations table.",
    "tags": [
      "Setup"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/setup/migrations/run",
    "summary": "Run pending migrations",
    "description": "Ensures schema migrations are applied by triggering the migration helper.",
    "tags": [
      "Setup"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/setup/reset",
    "summary": "Wipe and reset the database",
    "description": "Clears all data so init/seed can be rerun. Requires database admin role (JWT only).",
    "tags": [
      "Setup"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/setup/stripe",
    "summary": "Connect Stripe",
    "description": "Configure Stripe API keys for payment processing",
    "tags": [
      "Setup"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/tax-rates",
    "summary": "List all tax rates",
    "description": "Get a paginated list of tax rates",
    "tags": [
      "Tax Rates"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/tax-rates",
    "summary": "Create a new tax rate",
    "tags": [
      "Tax Rates"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/tax-rates/{id}",
    "summary": "Delete a tax rate",
    "tags": [
      "Tax Rates"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/tax-rates/{id}",
    "summary": "Get a tax rate",
    "tags": [
      "Tax Rates"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/tax-rates/{id}",
    "summary": "Update a tax rate",
    "tags": [
      "Tax Rates"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/webhooks",
    "summary": "List all webhooks",
    "tags": [
      "Webhooks"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/webhooks",
    "summary": "Create a webhook",
    "tags": [
      "Webhooks"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/webhooks/{id}",
    "summary": "Delete a webhook",
    "tags": [
      "Webhooks"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/webhooks/{id}",
    "summary": "Get webhook with recent deliveries",
    "tags": [
      "Webhooks"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/webhooks/{id}",
    "summary": "Update a webhook",
    "tags": [
      "Webhooks"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/webhooks/{id}/deliveries/{deliveryId}",
    "summary": "Get delivery details",
    "tags": [
      "Webhooks"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/webhooks/{id}/deliveries/{deliveryId}/retry",
    "summary": "Retry a failed delivery",
    "tags": [
      "Webhooks"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/webhooks/{id}/rotate-secret",
    "summary": "Rotate webhook secret",
    "tags": [
      "Webhooks"
    ]
  }
];
