// AUTO-GENERATED by generate.ts — do not edit manually.
// Each chunk has one 768-dim Float32 vector.

export const VECTOR_DIM = 768;
export const VECTOR_COUNT = 0; // Will be updated during generation

/**
 * Base64-encoded Float32 buffer, concatenated in chunk order.
 * Layout: [chunk0_v0, chunk0_v1, …, chunk0_v767, chunk1_v0, …]
 */
export const VECTORS_B64 = ""; // Will be populated during generation

/** Parallel array: chunk IDs in the same order as VECTORS_B64. */
export const CHUNK_IDS: readonly string[] = [];
