// Copyright (c) 2024-2026 Ronan LE MEILLAT
// License: AGPL-3.0-or-later
//
// OpenAPI 3.1 route parser — extracts routes from an OpenAPI document object.
// Replaces the old regex-based approach (which missed most routes registered
// through @hono/zod-openapi's createRoute() / app.openapi()).
//
// Source of truth: the openapi.json generated by OpenAPIHono.doc31() at runtime.

export type RouteInfo = {
  method: string;
  path: string;
  summary?: string;
  description?: string;
  tags?: string[];
  operationId?: string;
};

const HTTP_METHODS = ["get", "post", "put", "delete", "patch", "options", "head", "trace"] as const;

/**
 * Parse all routes from an OpenAPI 3.1 document object.
 * Iterates over `paths` and every HTTP method defined on each path item.
 *
 * @param openApiDoc - Parsed OpenAPI 3.1 JSON object
 * @returns Array of route definitions sorted by path then method
 */
export function parseOpenApiRoutes(openApiDoc: Record<string, unknown>): RouteInfo[] {
  const routes: RouteInfo[] = [];
  const paths = (openApiDoc?.paths ?? {}) as Record<string, Record<string, unknown>>;

  for (const [path, pathItem] of Object.entries(paths)) {
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method] as Record<string, unknown> | undefined;
      if (!operation) continue;

      routes.push({
        method: method.toUpperCase(),
        path,
        summary: operation.summary as string | undefined,
        description: operation.description as string | undefined,
        tags: operation.tags as string[] | undefined,
        operationId: operation.operationId as string | undefined,
      });
    }
  }

  return routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}
