/**
 * AUTO-GENERATED by apps/mcp/src/knowledge/generate.ts — do not edit manually.
 * This file is gitignored; it is rebuilt before every deploy.
 */
import type { TopicManifest } from './index.js';

export const MANIFEST: TopicManifest = {
  "generated_at": "2026-04-22T06:36:34.502Z",
  "commit": "761642f",
  "manifest_version": "1.0.0",
  "topics": [
    {
      "slug": "admin-crud-pattern",
      "title": "The Three-Component Architecture",
      "description": "Standardized admin list/edit architecture built from AdminCrudLayout, useAdminCrud hook, and RowActions — the three-part composition every admin page uses.",
      "tags": [
        "design",
        "theming"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1272,
      "sources_checksum": "78e4506c9f466658906205fb8ed705d0b2da8e5161507bd4b26d314c60045322"
    },
    {
      "slug": "ai-assisted-features",
      "title": "AI Implementation Architecture",
      "description": "AI-assisted features (review moderation, auto-translation) — GET /v1/ai/parameters endpoint, ai-client.ts helpers, and the browser-side inference pattern.",
      "tags": [
        "ai",
        "api",
        "backend",
        "hono",
        "i18n",
        "localization",
        "moderation",
        "reviews"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1080,
      "sources_checksum": "3ae4bcc02601403f46866b9bbd06610cf4b55d01ba8199734bd3bec5ee0dc3eb"
    },
    {
      "slug": "analytics-dashboard",
      "title": "Analytics API Endpoints",
      "description": "Merchant analytics surface — revenue, orders and traffic endpoints plus the chart wrappers rendered on the admin analytics page.",
      "tags": [
        "metrics",
        "observability"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1059,
      "sources_checksum": "45312b45e65b1217f4875d64a4f440b6fd01555c0903a0d16b880b7b4589338f"
    },
    {
      "slug": "api-error-patterns",
      "title": "The ApiError Class Structure",
      "description": "ApiError class and static helpers (notFound, unauthorized, invalidRequest, conflict…), Hono-to-JSON conversion, and frontend error-handling patterns.",
      "tags": [
        "general"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1125,
      "sources_checksum": "c8309686cd258995d7eddf8bbb36c770a655c93699c2fdafc51c1e48cfc7121e"
    },
    {
      "slug": "auth-patterns",
      "title": "Supported Token Formats",
      "description": "Backend authMiddleware, RBAC guards (adminOnly, superAdminOnly, databaseAdminOnly…), and the frontend AuthenticationGuardWithPermission wrapper used to gate admin pages.",
      "tags": [
        "auth",
        "auth0",
        "frontend",
        "react",
        "security",
        "ui"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1343,
      "sources_checksum": "14ed54aed6473e07554153e6ab655f394ecfbf575029b9d8c9ab04f0d8ea5428"
    },
    {
      "slug": "auth0-tenant-setup",
      "title": "Purpose and Execution",
      "description": "Auth0 tenant deployment — auto-install script, resource-server scopes, RBAC roles, social connections, and the Auth0 Deploy CLI workflow.",
      "tags": [
        "auth",
        "auth0",
        "ci",
        "security",
        "testing"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1062,
      "sources_checksum": "82b116e24f8015c516fe60060c659d366a7b2a36c4df88906b575cc8ca5648a8"
    },
    {
      "slug": "checkout-and-ucp",
      "title": "Universal Commerce Protocol (UCP)",
      "description": "Checkout flow and the Universal Commerce Protocol (UCP) — Stripe Checkout integration, UCP sessions, browse/catalog endpoints consumed by AI shopping agents.",
      "tags": [
        "ai-agents",
        "api",
        "checkout",
        "integration",
        "payments",
        "stripe",
        "ucp"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1285,
      "sources_checksum": "8097941bca7cd53a32f95b7ec0a35cb703fe2b9f3a1888450480a60ea10b2521"
    },
    {
      "slug": "cloudflare-worker-patterns",
      "title": "Accessing Cloudflare Bindings in Hono",
      "description": "Cloudflare Worker building blocks: Durable Objects with SQLite, KV, R2, Rate Limiter bindings, wrangler.jsonc layout, and CI secrets handling.",
      "tags": [
        "ci",
        "cloudflare",
        "database",
        "durable-object",
        "images",
        "schema",
        "storage",
        "testing"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1165,
      "sources_checksum": "bd08b301cf5e11c884dabe72acf99f5e642ef0f10dffe8c29aa8256f8d755e39"
    },
    {
      "slug": "conventions-and-anti-patterns",
      "title": "CONVENTIONS",
      "description": "Fufuni coding conventions and forbidden patterns — naming rules, no c.req.json, no Drizzle, Zod-in-createRoute, plus AI-agent contributor guidelines.",
      "tags": [
        "ai-agents",
        "frontend",
        "react",
        "ucp",
        "ui"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 991,
      "sources_checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    },
    {
      "slug": "customer-account-patterns",
      "title": "Customer Authentication and Middleware",
      "description": "Customer account surface: /me routes, customerAuthMiddleware, address book, order history, and profile-update flows for logged-in shoppers.",
      "tags": [
        "account",
        "api",
        "auth",
        "auth0",
        "backend",
        "cloudflare",
        "commerce",
        "hono",
        "images",
        "orders",
        "security",
        "storage",
        "user"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1485,
      "sources_checksum": "2bc43f33b2fe27b52cf93aa9cc08773f708de0ffe41404458a897d107ed99b56"
    },
    {
      "slug": "db-schema",
      "title": "Durable Object Persistence Pattern",
      "description": "Complete Durable Object SQL schema — every table, column, index and foreign key used by the Fufuni backend.",
      "tags": [
        "database",
        "durable-object",
        "schema"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1678,
      "sources_checksum": "56e619248dd1546776ba5d7f77399678d0d129a51d5bbaf54e10eb79e53acce4"
    },
    {
      "slug": "discounts-and-pricing",
      "title": "Discount Types and Schema",
      "description": "Discount codes and tiered pricing — lib/pricing.ts helpers, promotion endpoints, and the discount-application order for cart totals.",
      "tags": [
        "ci",
        "commerce",
        "pricing",
        "testing"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1284,
      "sources_checksum": "8ef76494fb84f2e5e30faf75516bdce5711536e0b7d4ed81cefd98fb184bc7e8"
    },
    {
      "slug": "e2e-testing",
      "title": "E2E Project Structure",
      "description": "Playwright end-to-end setup — fixtures, storage-state auth reuse, test specs under e2e/, and helper scripts that seed a temporary store.",
      "tags": [
        "ci",
        "cloudflare",
        "data",
        "images",
        "storage",
        "testing"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1043,
      "sources_checksum": "aa55552fb2d70ac8a236a366ec40495053dd74d38cb931f924ae092bec566e7a"
    },
    {
      "slug": "email-templates",
      "title": "Mailgun Infrastructure",
      "description": "Transactional email delivery via Mailgun — Handlebars templates (order confirmation, password reset, refund), sending helpers, and trigger points.",
      "tags": [
        "commerce",
        "email",
        "mailgun",
        "orders"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1149,
      "sources_checksum": "0ae646504fa394dac20e70999ada7517f5e787be2bf359cb7fa00471dc1b9659"
    },
    {
      "slug": "framework-overview",
      "title": "🛠 Technology Stack",
      "description": "High-level Fufuni architecture — stack (CF Workers + Durable Objects + React), monorepo layout, request lifecycle, and core conventions. Start here.",
      "tags": [
        "cloudflare",
        "images",
        "storage"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1305,
      "sources_checksum": "c7355b78247db878ab5683509da3f5b862453f7f739932011d3952ac1761bddf"
    },
    {
      "slug": "frontend-react-patterns",
      "title": "Application Architecture & Providers",
      "description": "React 19 patterns on the merchant UI — React Query defaults, HeroUI v3 components, client routing, custom hooks, navbar wiring, and theme integration.",
      "tags": [
        "design",
        "frontend",
        "react",
        "theming",
        "ui"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 997,
      "sources_checksum": "acdd966e39076c2e6ccc795a2b75ef734b85e8f8cd4065bb7ee34bdd419d00a5"
    },
    {
      "slug": "how-to-add-hono-route",
      "title": "Anatomy of a Fufuni Route File",
      "description": "Step-by-step pattern for adding a new OpenAPIHono route — Zod schemas, public vs admin split (publicApp + adminApp export), and RBAC guards.",
      "tags": [
        "api",
        "backend",
        "hono"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1392,
      "sources_checksum": "fdd0178e846e43d73fa0dc3dee8208b99e1b82e5b3596d3946d7fb99cfd5dfe4"
    },
    {
      "slug": "how-to-add-migration",
      "title": "The Triple-Entry Schema Pattern",
      "description": "Step-by-step pattern for changing the DB schema — update SCHEMA constant, append to ensureInitialized, add numbered SQL file under apps/merchant/migrations/.",
      "tags": [
        "cloudflare",
        "database",
        "frontend",
        "images",
        "migrations",
        "react",
        "schema",
        "storage",
        "ui"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1241,
      "sources_checksum": "1786b0e4b75821b712f4fc67d23488ad6fa1b89de759027378c9bb210a5721af"
    },
    {
      "slug": "i18n-patterns",
      "title": "Locale Architecture and File Structure",
      "description": "react-i18next usage across the six supported locales — locale files layout, useTranslation hook, and fallback-language behaviour.",
      "tags": [
        "frontend",
        "i18n",
        "localization",
        "react",
        "ui"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1092,
      "sources_checksum": "3194a34395ce4e12311474189ce379dc3fafe51eade7f5b201cc5f1e423972c3"
    },
    {
      "slug": "image-storage-patterns",
      "title": "Image Storage Architecture",
      "description": "Image upload and display — base64-in-SQL vs R2-hosted trade-off, ImageUploadInput component, uploadImageFile utility, and URL resolution.",
      "tags": [
        "cloudflare",
        "frontend",
        "images",
        "react",
        "storage",
        "ui"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1208,
      "sources_checksum": "2dcbb58154063e3e67378af551fdad0de7448dced3944c2c9ea4a171497c2adc"
    },
    {
      "slug": "inventory-and-warehouses",
      "title": "Data Model and Schema",
      "description": "Stock tracking per variant × warehouse — inventory table, reserveStock/releaseStock/deductStock helpers in lib/inventory.ts, and the admin adjustment UI.",
      "tags": [
        "inventory",
        "warehouse"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1246,
      "sources_checksum": "8fc3714b3df6fdf44b6061fb91f4423df5f196b4b74b595155c00d13a52a62b2"
    },
    {
      "slug": "invoice-and-pdf",
      "title": "PDF Generation Engine",
      "description": "Client-side PDF invoice generation with jsPDF — invoice layout, order-view tokens for public access, and the download entry point.",
      "tags": [
        "commerce",
        "documents",
        "invoicing",
        "orders"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1047,
      "sources_checksum": "90207c0a5c6d62a1ed2883b8a31b2e4f2d3130a39ad4a1c2f19cbe8bd8be8f80"
    },
    {
      "slug": "jwt-user-metadata-patterns",
      "title": "The `useTokenUserData` Hook",
      "description": "Auth0 JWT custom claims — user_metadata vs app_metadata, useTokenUserData hook, store-metadata propagation, and per-user theme storage.",
      "tags": [
        "auth",
        "auth0",
        "cloudflare",
        "images",
        "security",
        "storage"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1190,
      "sources_checksum": "6ed351c174ef894e52e0afd2f3b476cde7be76c0680f3d47f1f5a85a45928ce7"
    },
    {
      "slug": "localized-content-patterns",
      "title": "LocalizedText Structure and Storage",
      "description": "Multilingual content model — LocalizedText type, useLocalizedTextInput hook, and the renderLocalized utility used across product and category surfaces.",
      "tags": [
        "general"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1061,
      "sources_checksum": "86ccda609673ce16c145932e6395bf14a1edf9607a692f63d735ceb7766e8189"
    },
    {
      "slug": "mcp-server-quickstart",
      "title": "Understanding the Fufuni MCP Server",
      "description": "Setup and extension of the Fufuni MCP server itself — generate.ts pipeline, adding a new topic, running gen-knowledge, and deploying to Cloudflare.",
      "tags": [
        "frontend",
        "react",
        "ui"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1256,
      "sources_checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    },
    {
      "slug": "migrations-reference",
      "title": "Durable Object Schema Management",
      "description": "Enumeration of every numbered SQL migration — applied order, schema changes introduced, and a mini changelog per migration file.",
      "tags": [
        "commerce",
        "database",
        "durable-object",
        "migrations",
        "orders",
        "schema"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1381,
      "sources_checksum": "16180139cea84c08f0259fa1cccaf6961e0211d4d84c0e100c61725cadc2422a"
    },
    {
      "slug": "oauth-embedded",
      "title": "Purpose of the Embedded OAuth2 Server",
      "description": "Embedded OAuth2 authorization server — client registration, token issuance, scopes, introspection endpoint, and integration with external apps.",
      "tags": [
        "api",
        "auth",
        "auth0",
        "integration",
        "security"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1144,
      "sources_checksum": "dcd38fe40a28b1ec43840e97330a397599a89badf25571d6ddb91fa4a5f153df"
    },
    {
      "slug": "order-view-tokens",
      "title": "Purpose of Order View Tokens",
      "description": "Signed order-view tokens — how they are generated, how the public invoice route validates them, and when to use them instead of JWT auth.",
      "tags": [
        "commerce",
        "documents",
        "invoicing",
        "orders"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1220,
      "sources_checksum": "884067771ab7197f81117832376199667a65bd14d22069f7fff10394a9f2e494"
    },
    {
      "slug": "orders-and-refunds",
      "title": "Order Lifecycle & Status Machine",
      "description": "Order lifecycle (pending → paid → fulfilled → refunded), partial-refund audit trail from migration 034, and the CSV export endpoint.",
      "tags": [
        "checkout",
        "commerce",
        "orders",
        "payments",
        "stripe"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1219,
      "sources_checksum": "eb53db1e9955527f852119537504aa90f26f026f1ba3bfa6ecc5e93d44d19c47"
    },
    {
      "slug": "product-catalog-and-localization",
      "title": "Product Model and Image Structure",
      "description": "Product catalogue — CRUD endpoints, variant management, category tree, and how product names and descriptions are localized per store locale.",
      "tags": [
        "catalog",
        "products"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1291,
      "sources_checksum": "b068fbeb6459190109571a250e36b7ecbe137668fb4019e3412f9f426b92ce2a"
    },
    {
      "slug": "product-reviews",
      "title": "Product Review Data Model",
      "description": "Product review system — customer submission, rating aggregation, AI-assisted moderation, and the admin review management page.",
      "tags": [
        "ai",
        "catalog",
        "moderation",
        "products",
        "reviews"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1185,
      "sources_checksum": "2eee616dc080feadb370714430679d82816ea4f80d7c5712389864056f03e008"
    },
    {
      "slug": "regions-taxes-shipping",
      "title": "Regions and Geographic Mapping",
      "description": "Regions, tax rates, and shipping zones — lib/tax.ts and lib/shipping.ts helpers, rate tables, and region → shipping-zone mapping.",
      "tags": [
        "commerce",
        "pricing"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1349,
      "sources_checksum": "cb787dab5f95e570bb448ebb6629b87c3b36c5973a02833673395010ff9657aa"
    },
    {
      "slug": "seed-data-patterns",
      "title": "Execution and CLI Arguments",
      "description": "Seed script structure — how demo data is inserted, how to add new seed records, and the reset-demo GitHub Action that triggers it on a schedule.",
      "tags": [
        "data",
        "testing"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1079,
      "sources_checksum": "b37261fe66600a58c044f4bbac69cf6fb86284246d31581356ea52ac7b2679ad"
    },
    {
      "slug": "setup-and-initialization",
      "title": "Checking Initialization Status",
      "description": "First-run store setup — the /v1/setup endpoint, initial-configuration fields, and the routes that bootstrap a fresh Fufuni instance.",
      "tags": [
        "api",
        "backend",
        "hono"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1222,
      "sources_checksum": "d420780a7f62cd976b551e4648abe5426af604127f67dc7b51f137ea98ed6789"
    },
    {
      "slug": "theming-and-layouts",
      "title": "Core Layout Architectures",
      "description": "Theme and layout system — ThemeProvider, the Default and Luxury layouts, CMS-driven content blocks, and siteConfig integration.",
      "tags": [
        "design",
        "frontend",
        "react",
        "theming",
        "ui"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1103,
      "sources_checksum": "14f33a2d52fb5deaa8f6481d6d0ecf72e541543b10b70a728c03c679c4741bfc"
    },
    {
      "slug": "use-secured-api",
      "title": "Import path",
      "description": "useSecuredApi React hook for authenticated calls — getJson, postJson, putJson, patchJson, deleteJson, postForm, plus Auth0 bearer injection.",
      "tags": [
        "frontend",
        "react",
        "ui"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1150,
      "sources_checksum": "1f3c4784272a2d1bf03e7deb3a9150133130e03730a11ad6a6c8922d20d9e954"
    },
    {
      "slug": "user-preferences-and-wishlist",
      "title": "User Persistence Architecture",
      "description": "Per-user state — wishlist stored in Auth0 user_metadata, saved carts, and the custom hooks that wrap the metadata updates.",
      "tags": [
        "account",
        "auth",
        "auth0",
        "security",
        "user"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1013,
      "sources_checksum": "5f81fa0ccca254095d593a9ae2e4d4890f135cfc78b287a128ee336a91c7f3c8"
    },
    {
      "slug": "webhooks-outbound",
      "title": "Outbound Webhooks Overview",
      "description": "Outbound webhooks — endpoint registration, delivery retry logic, and the HMAC signature scheme used by consumers to verify authenticity.",
      "tags": [
        "events",
        "webhooks"
      ],
      "updated_at": "2026-04-22T06:36:34.502Z",
      "word_count": 1130,
      "sources_checksum": "92b2559bd014a0f161ed6e3e69b093d8f10d2bb251c8601ac343332a6efbc33e"
    }
  ]
};
