/**
 * AUTO-GENERATED by apps/mcp/src/knowledge/generate.ts — do not edit manually.
 * This file is gitignored; it is rebuilt before every deploy.
 */
import type { TopicManifest } from './index.js';

export const MANIFEST: TopicManifest = {
  "generated_at": "2026-04-23T19:39:26.124Z",
  "commit": "65b90bd",
  "manifest_version": "1.0.0",
  "topics": [
    {
      "slug": "ai-assisted-features",
      "title": "AI-Assisted Features Reference",
      "description": "AI-assisted features (review moderation, auto-translation) — GET /v1/ai/parameters endpoint, ai-client.ts helpers, and the browser-side inference pattern.",
      "tags": [
        "ai",
        "api",
        "backend",
        "hono",
        "i18n",
        "localization",
        "moderation",
        "reviews"
      ],
      "updated_at": "2026-04-23T19:39:26.124Z",
      "word_count": 1133,
      "sources_checksum": "8b6a6c1fa39a12604e6b50e59e55caa5168d2b77ab46feb983d41f25bcee0833"
    }
  ]
};
