#!/usr/bin/env tsx
/// <reference types="node" />
// Copyright (c) 2024-2026 Ronan LE MEILLAT
// License: AGPL-3.0-or-later
//
// Build script: embeds whitelisted source files into apps/mcp/src/sources.ts
// Run before deploying the Worker to update embedded sources.
//
// Usage:
//   npx tsx apps/mcp/scripts/build-sources.ts
//   # or via npm script:
//   npm run build:sources

import { readFile, writeFile, mkdir, readdir } from "fs/promises";
import { join, dirname } from "path";
import { execSync } from "child_process";
import { fileURLToPath } from "url";
import { parseOpenApiRoutes } from "../src/lib/route-parser.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const repoRoot = join(__dirname, "../../..");
const outputFile = join(__dirname, "../src/sources.ts");
const whitelistFile = join(__dirname, "../src/sources-whitelist.ts");
const topicSourcesDir = join(__dirname, "../src/knowledge/topics");

const MANUAL_READABLE_SOURCES = [
  // Merchant Worker — Core
  "apps/merchant/src/do.ts",
  "apps/merchant/src/index.ts",
  "apps/merchant/src/types.ts",
  "apps/merchant/src/db.ts",
  "apps/merchant/src/schemas.ts",
  
  // Merchant Routes (selection)
  "apps/merchant/src/routes/categories.ts",
  "apps/merchant/src/routes/catalog.ts",
  "apps/merchant/src/routes/checkout.ts",
  "apps/merchant/src/routes/customers.ts",
  "apps/merchant/src/routes/orders.ts",
  "apps/merchant/src/routes/webhooks.ts",
  "apps/merchant/src/routes/inventory.ts",
  "apps/merchant/src/routes/auth0.ts",
  
  // Merchant Middleware
  "apps/merchant/src/middleware/auth.ts",
  "apps/merchant/src/middleware/customer-auth.ts",
  "apps/merchant/src/middleware/rate-limit.ts",
  "apps/merchant/src/middleware/kv-cache.ts",
  
  // Merchant Utils/Libs
  "apps/merchant/src/lib/auth0.ts",
  "apps/merchant/src/lib/pricing.ts",
  "apps/merchant/src/lib/tax.ts",
  "apps/merchant/src/lib/shipping.ts",
  "apps/merchant/src/lib/webhooks.ts",
  "apps/merchant/src/lib/inventory.ts",
  
  // Client App — Core
  "apps/client/src/app.tsx",
  "apps/client/src/provider.tsx",
  "apps/client/src/config/site.ts",
  
  // Client Authentication
  "apps/client/src/authentication/index.ts",
  
  // Client Layouts
  "apps/client/src/layouts/default.tsx",
  
  // Database Migrations (latest 5)
  "apps/merchant/migrations/034-enrich-refunds.sql",
  "apps/merchant/migrations/033-order-email-settings-add-pending-paid.sql",
  "apps/merchant/migrations/032-order-email-settings.sql",
  "apps/merchant/migrations/030-add-store-themes.sql",
  "apps/merchant/migrations/029-variants-add-thumbnail-url.sql",
];

async function collectTopicSources(): Promise<string[]> {
  const topicFiles = await readdir(topicSourcesDir);
  const result = new Set<string>();

  for (const file of topicFiles) {
    if (!file.endsWith(".ts")) continue;
    const content = await readFile(join(topicSourcesDir, file), "utf-8");
    const match = content.match(/sources\s*:\s*\[((?:.|\n)*?)\]/m);
    if (!match) continue;

    const sourceBlock = match[1];
    for (const item of sourceBlock.matchAll(/['\"]([^'\"]+)['\"]/g)) {
      result.add(item[1]);
    }
  }

  return [...result].sort();
}

function buildWhitelistContent(paths: string[]): string {
  const lines = [
    "// @nocontext — exclude this file from AI context windows (Copilot, Continue, Cursor)",
    "// Copyright (c) 2024-2026 Ronan LE MEILLAT",
    "// License: AGPL-3.0-or-later",
    "//",
    "// AUTO-GENERATED by apps/mcp/scripts/build-sources.ts",
    "// Do not edit manually — run: npm run build:sources",
    "",
    "export const READABLE_SOURCES: ReadonlyArray<string> = [",
  ];

  for (const path of paths) {
    lines.push(`  ${JSON.stringify(path)},`);
  }

  lines.push("];", "", "// Note: Files that don't exist will be skipped gracefully during build:sources.", "");
  return lines.join("\n");
}

function isGitIgnored(path: string): boolean {
  try {
    execSync(`git check-ignore --quiet -- "${path}"`, {
      cwd: repoRoot,
      stdio: "ignore",
    });
    return true;
  } catch {
    return false;
  }
}

function filterIgnoredPaths(paths: string[]): string[] {
  const ignored: string[] = [];
  const kept: string[] = [];

  for (const path of paths) {
    if (isGitIgnored(path)) {
      ignored.push(path);
    } else {
      kept.push(path);
    }
  }

  if (ignored.length > 0) {
    console.warn(`Skipping ${ignored.length} gitignored path(s):`);
    for (const path of ignored) {
      console.warn(`  - ${path}`);
    }
  }

  return kept;
}

// Ensure src/ exists
await mkdir(dirname(outputFile), { recursive: true });

const sources: Record<string, string> = {};
const commits: Record<string, string> = {};
const failed: string[] = [];

const topicSources = await collectTopicSources();
const readableSources = filterIgnoredPaths(
  Array.from(new Set([...MANUAL_READABLE_SOURCES, ...topicSources])).sort(),
);

await writeFile(whitelistFile, buildWhitelistContent(readableSources), "utf-8");
console.log(`Wrote ${readableSources.length} whitelisted paths to ${whitelistFile}`);
console.log(`Building sources from ${readableSources.length} whitelisted files...`);

for (const path of readableSources) {
  const fullPath = join(repoRoot, path);

  try {
    const content = await readFile(fullPath, "utf-8");
    sources[path] = content;

    // Try to get short commit hash for this file
    try {
      const hash = execSync(`git log -n1 --format=%h -- "${path}"`, {
        cwd: repoRoot,
        encoding: "utf-8",
      }).trim();
      commits[path] = hash || "unknown";
    } catch {
      commits[path] = "unknown";
    }

    process.stdout.write(".");
  } catch (err) {
    console.error(`\n✗ Failed to read ${path}: ${(err as Error).message}`);
    failed.push(path);
  }
}

console.log("\n");

const lines = [
  "// Copyright (c) 2024-2026 Ronan LE MEILLAT",
  "// License: AGPL-3.0-or-later",
  "//",
  "// AUTO-GENERATED by apps/mcp/scripts/build-sources.ts",
  "// Do not edit manually — run: npm run build:sources",
  "// This file is gitignored and rebuilt on every deploy.",
  "",
  "/**",
  " * Whitelisted source files embedded in the Worker bundle.",
  " * Each file is indexed by its repo-relative path.",
  " */",
  "export const SOURCES: Record<string, string> = {",
];

// Sort paths for consistency
const sortedPaths = Object.keys(sources).sort();
for (const path of sortedPaths) {
  const escaped = JSON.stringify(sources[path]);
  lines.push(`  [${JSON.stringify(path)}]: ${escaped},`);
}

lines.push("};", "");
lines.push("/**", " * Per-file commit hashes (short SHA) at build time.", " */");
lines.push("export const SOURCE_COMMITS: Record<string, string> = {");

for (const path of sortedPaths) {
  lines.push(`  [${JSON.stringify(path)}]: ${JSON.stringify(commits[path])},`);
}

lines.push("};", "");

await writeFile(outputFile, lines.join("\n"), "utf-8");

console.log(`✓ Embedded ${sortedPaths.length} source files → src/sources.ts`);

if (failed.length > 0) {
  console.warn(`\n⚠ ${failed.length} file(s) failed to read:`);
  for (const path of failed) {
    console.warn(`  - ${path}`);
  }
  process.exit(1);
}

// ── Generate src/search/routes.ts from openapi.json ─────────────────────────
const openApiPath = join(repoRoot, "openapi.json");
const routesOutputFile = join(__dirname, "../src/search/routes.ts");

try {
  const openApiContent = await readFile(openApiPath, "utf-8");
  const openApiDoc = JSON.parse(openApiContent) as Record<string, unknown>;
  const routes = parseOpenApiRoutes(openApiDoc);

  const routeLines = [
    "// Copyright (c) 2024-2026 Ronan LE MEILLAT",
    "// License: AGPL-3.0-or-later",
    "//",
    "// AUTO-GENERATED by apps/mcp/scripts/build-sources.ts",
    "// Do not edit manually — run: npm run build:sources",
    "// Requires openapi.json at repo root (run: cd apps/merchant && npm run gen:openapi)",
    "",
    `import type { RouteInfo } from "../lib/route-parser.js";`,
    "",
    "/**",
    " * All API routes extracted from openapi.json (generated by OpenAPIHono.doc31 at runtime).",
    " * Updated at build time — reflects the full route surface, not a regex approximation.",
    " */",
    "export const ROUTES: RouteInfo[] = " + JSON.stringify(routes, null, 2) + ";",
    "",
  ];

  await writeFile(routesOutputFile, routeLines.join("\n"), "utf-8");
  console.log(`✓ Extracted ${routes.length} routes from openapi.json → src/search/routes.ts`);
} catch (err) {
  const isNotFound = (err as NodeJS.ErrnoException).code === "ENOENT";
  if (isNotFound) {
    console.warn("\n⚠ openapi.json not found at repo root.");
    console.warn("  Generate it first: cd apps/merchant && npm run gen:openapi");
    console.warn("  Then re-run: npm run build:sources");
  } else {
    console.error(`\n✗ Failed to parse openapi.json: ${(err as Error).message}`);
  }

  // Write empty stub so the Worker still compiles without routes
  const stub = [
    "// Copyright (c) 2024-2026 Ronan LE MEILLAT",
    "// License: AGPL-3.0-or-later",
    "//",
    "// AUTO-GENERATED — run: npm run build:sources",
    "// To populate: cd apps/merchant && npm run gen:openapi",
    "",
    `import type { RouteInfo } from "../lib/route-parser.js";`,
    "",
    "export const ROUTES: RouteInfo[] = [];",
    "",
  ].join("\n");
  await writeFile(routesOutputFile, stub, "utf-8");
}
