#!/usr/bin/env tsx
// Copyright (c) 2024-2026 Ronan LE MEILLAT
// License: AGPL-3.0-or-later
//
// Reads all *.md files from the monorepo mcp/ directory and generates
// apps/mcp/src/knowledge.ts — a static Record<slug, markdown-content> bundle
// that is imported by the MCP Worker at build time (no runtime I/O needed).
//
// Usage (from any directory):
//   npx tsx apps/mcp/scripts/gen-knowledge.ts
//   # or via npm script from apps/mcp/:
//   npm run gen-knowledge

import { readdir, readFile, writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { join, extname, basename, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const mcpDir = join(__dirname, "../../../mcp");
const outputFile = join(__dirname, "../src/knowledge.ts");

// Ensure src/ exists
await mkdir(dirname(outputFile), { recursive: true });

if (!existsSync(mcpDir)) {
  console.warn(`⚠  mcp/ directory not found at ${mcpDir} — generating empty knowledge module.`);
  await writeFile(
    outputFile,
    [
      "// AUTO-GENERATED — no knowledge files found.",
      "// Run the MCP generate script first: npm run mcp:generate",
      "",
      "export const KNOWLEDGE: Record<string, string> = {};",
      "",
    ].join("\n"),
    "utf-8",
  );
  process.exit(0);
}

const files = (await readdir(mcpDir)).filter((f) => extname(f) === ".md").sort();

if (files.length === 0) {
  console.warn("⚠  No .md files found in mcp/ — generating empty knowledge module.");
}

const entries: [string, string][] = [];
for (const file of files) {
  const slug = basename(file, ".md");
  const content = await readFile(join(mcpDir, file), "utf-8");
  entries.push([slug, content]);
}

const lines: string[] = [
  "// AUTO-GENERATED by apps/mcp/scripts/gen-knowledge.ts",
  "// Do not edit manually — run: npm run gen-knowledge",
  "// This file is gitignored; it is rebuilt before every deploy.",
  "",
  "export const KNOWLEDGE: Record<string, string> = {",
];

for (const [slug, content] of entries) {
  lines.push(`  ${JSON.stringify(slug)}: ${JSON.stringify(content)},`);
}

lines.push("};", "");

await writeFile(outputFile, lines.join("\n"), "utf-8");
console.log(`✓ Generated ${entries.length} topics → src/knowledge.ts`);
