#!/usr/bin/env tsx
/// <reference types="node" />
// Copyright (c) 2024-2026 Ronan LE MEILLAT
// License: AGPL-3.0-or-later
//
// Reads all *.md files from the monorepo mcp/ directory and generates
// apps/mcp/src/knowledge.ts — a static Record<slug, markdown-content> bundle
// and apps/mcp/src/search/vectors.ts — a static embedding index for the content,
// that is imported by the MCP Worker at build time (no runtime I/O needed).
//
// Usage (from any directory):
//   npx tsx apps/mcp/scripts/gen-knowledge.ts
//   # or via npm script from apps/mcp/:
//   npm run gen-knowledge

import { readdir, readFile, writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { join, extname, basename, dirname } from "path";
import { fileURLToPath } from "url";
import {
  generateEmbedding,
  normalizeVector,
  buildVectorsModule,
  buildApiKeyPool,
  createRoundRobinKeyProvider,
} from "../src/lib/generate-knowledge.js";
import { decryptAiConfig, type AiConfig } from "../src/lib/ai-enc.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const mcpDir = join(__dirname, "../knowledge/generated"); // Relative to this script
const outputFile = join(__dirname, "../src/knowledge.ts");

// Ensure src/ exists
await mkdir(dirname(outputFile), { recursive: true });

if (!existsSync(mcpDir)) {
  console.warn(`⚠  mcp/ directory not found at ${mcpDir} — generating empty knowledge module.`);
  await writeFile(
    outputFile,
    [
      "// AUTO-GENERATED — no knowledge files found.",
      "// Run the MCP generate script first: npm run mcp:generate",
      "// If you set CRYPTOKEN and apps/mcp/src/config/ai.json.enc, this script will decrypt it in memory and generate embeddings using the configured Gemini keys.",
      "",
      "export const KNOWLEDGE: Record<string, string> = {};",
      "",
    ].join("\n"),
    "utf-8",
  );
  process.exit(0);
}

const files = (await readdir(mcpDir)).filter((f) => extname(f) === ".md").sort();

if (files.length === 0) {
  console.warn("⚠  No .md files found in mcp/ — generating empty knowledge module.");
}

const entries: [string, string][] = [];
for (const file of files) {
  const slug = basename(file, ".md");
  const content = await readFile(join(mcpDir, file), "utf-8");
  entries.push([slug, content]);
}

const lines: string[] = [
  "// AUTO-GENERATED by apps/mcp/scripts/gen-knowledge.ts",
  "// Do not edit manually — run: npm run gen-knowledge",
  "// This file is gitignored; it is rebuilt before every deploy.",
  "",
  "export const KNOWLEDGE: Record<string, string> = {",
];

for (const [slug, content] of entries) {
  lines.push(`  ${JSON.stringify(slug)}: ${JSON.stringify(content)},`);
}

lines.push("};", "");

await writeFile(outputFile, lines.join("\n"), "utf-8");
console.log(`✓ Generated ${entries.length} topics → src/knowledge.ts`);

const vectorsOutputDir = join(__dirname, "../src/search");
await mkdir(vectorsOutputDir, { recursive: true });
const vectorsPath = join(vectorsOutputDir, "vectors.ts");

async function loadEncryptedAiConfig(): Promise<AiConfig | null> {
  const cryptoken = process.env.CRYPTOKEN;
  if (!cryptoken) return null;

  const configPath = join(__dirname, "../src/config/ai.json.enc");
  if (!existsSync(configPath)) return null;

  const encrypted = await readFile(configPath, "utf-8");
  return await decryptAiConfig(encrypted, cryptoken);
}

const aiConfig = await loadEncryptedAiConfig();
if (!aiConfig) {
  console.warn('⚠ CRYPTOKEN or apps/mcp/src/config/ai.json.enc is not configured; skipping vector generation.');
  process.exit(0);
}

const keyPool = buildApiKeyPool(aiConfig, { protocol: 'gemini' });
if (keyPool.length === 0) {
  console.warn('⚠ No Gemini API keys found in ai.json.enc; skipping vector generation.');
  process.exit(0);
}

const nextKey = createRoundRobinKeyProvider(keyPool);
const embeddings: number[][] = [];
const chunkIds: string[] = [];

for (const [slug, content] of entries) {
  process.stdout.write(`Embedding ${slug}... `);
  const firstKey = nextKey();
  const embedding = await generateEmbedding(content, {
    fetch,
    apiKey: firstKey.key,
    nextKey,
    model: 'gemini-embedding-001',
  });

  if (!embedding) {
    console.warn('failed');
    continue;
  }

  const normalized = normalizeVector(embedding);
  embeddings.push(normalized);
  chunkIds.push(`${slug}#0`);
  console.log('ok');
}

if (embeddings.length > 0) {
  const vectorModule = buildVectorsModule(embeddings, chunkIds, embeddings[0].length);
  await writeFile(vectorsPath, vectorModule, 'utf-8');
  console.log(`✓ Generated ${embeddings.length} embeddings → src/search/vectors.ts`);
} else {
  console.warn('⚠ No embeddings generated; skipping src/search/vectors.ts creation.');
}
