#!/usr/bin/env tsx
/// <reference types="node" />
// Copyright (c) 2024-2026 Ronan LE MEILLAT
// License: AGPL-3.0-or-later
//
// Reads all *.md files from the monorepo mcp/ directory and generates
// apps/mcp/src/knowledge.ts — a static Record<slug, markdown-content> bundle
// and apps/mcp/src/search/vectors.ts — a static embedding index for the content,
// that is imported by the MCP Worker at build time (no runtime I/O needed).
//
// Usage (from any directory):
//   npx tsx apps/mcp/scripts/gen-knowledge.ts
//   # or via npm script from apps/mcp/:
//   npm run gen-knowledge

import { readdir, readFile, writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { join, extname, basename, dirname } from "path";
import { fileURLToPath } from "url";
import {
  generateEmbedding,
  normalizeVector,
  buildVectorsModule,
  buildApiKeyPool,
  EmbeddingResult,
  summarizeEmbeddingStats,
  maskApiKey,
} from "../src/lib/generate-knowledge.js";
import { decryptAiConfig, type AiConfig } from "../src/lib/ai-enc.js";

// This script is intended to run in a developer machine or CI environment.
// It generates two build-time artifacts:
// 1) src/knowledge.ts : a static bundle of all generated Markdown topic files.
// 2) src/search/vectors.ts : a static embedding index for the same content.
// The Worker imports these files directly at build time, so there is no runtime
// file system access inside the Cloudflare Worker for knowledge or vector search.

const VECTOR_DIM = 256 ;//768; // Gemini embedding dimension
const VECTOR_MODEL = 'gemini-embedding-2-preview'; //'gemini-embedding-001'; // Gemini embedding model to use

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const mcpDir = join(__dirname, "../knowledge/generated"); // Relative to this script
const outputFile = join(__dirname, "../src/knowledge.ts");

// Ensure src/ exists
await mkdir(dirname(outputFile), { recursive: true });

if (!existsSync(mcpDir)) {
  console.warn(`⚠  mcp/ directory not found at ${mcpDir} — generating empty knowledge module.`);
  await writeFile(
    outputFile,
    [
      "// AUTO-GENERATED — no knowledge files found.",
      "// Run the MCP generate script first: npm run mcp:generate",
      "// If you set CRYPTOKEN and apps/mcp/src/config/ai.json.enc, this script will decrypt it in memory and generate embeddings using the configured Gemini keys.",
      "",
      "export const KNOWLEDGE: Record<string, string> = {};",
      "",
    ].join("\n"),
    "utf-8",
  );
  process.exit(0);
}

const files = (await readdir(mcpDir)).filter((f) => extname(f) === ".md").sort();

if (files.length === 0) {
  console.warn("⚠  No .md files found in mcp/ — generating empty knowledge module.");
}

const entries: [string, string][] = [];
for (const file of files) {
  const slug = basename(file, ".md");
  const content = await readFile(join(mcpDir, file), "utf-8");
  entries.push([slug, content]);
}

const lines: string[] = [
  "// AUTO-GENERATED by apps/mcp/scripts/gen-knowledge.ts",
  "// Do not edit manually — run: npm run gen-knowledge",
  "// This file is gitignored; it is rebuilt before every deploy.",
  "",
  "export const KNOWLEDGE: Record<string, string> = {",
];

for (const [slug, content] of entries) {
  lines.push(`  ${JSON.stringify(slug)}: ${JSON.stringify(content)},`);
}

lines.push("};", "");

await writeFile(outputFile, lines.join("\n"), "utf-8");
console.log(`✓ Generated ${entries.length} topics → src/knowledge.ts`);

const vectorsOutputDir = join(__dirname, "../src/search");
await mkdir(vectorsOutputDir, { recursive: true });
const vectorsPath = join(vectorsOutputDir, "vectors.ts");

async function loadEncryptedAiConfig(): Promise<AiConfig | null> {
  // The encrypted AI config file contains provider credentials.
  // This script decrypts it in memory using the CRYPTOKEN environment variable.
  // The decrypted result is never written to disk.
  const cryptoken = process.env.CRYPTOKEN;
  if (!cryptoken) return null;

  const configPath = join(__dirname, "../src/config/ai.json.enc");
  if (!existsSync(configPath)) return null;

  const encrypted = await readFile(configPath, "utf-8");
  return await decryptAiConfig(encrypted, cryptoken);
}

const aiConfig = await loadEncryptedAiConfig();
if (!aiConfig) {
  console.warn('⚠ CRYPTOKEN or apps/mcp/src/config/ai.json.enc is not configured; skipping vector generation.');
  process.exit(0);
}

// Build a pool of Gemini API keys from the decrypted config.
// buildApiKeyPool deduplicates the keys and shuffles them so that
// repeated calls will spread traffic across multiple key owners.
const keyPool = buildApiKeyPool(aiConfig, { protocol: 'gemini' });
if (keyPool.length === 0) {
  console.warn('⚠ No Gemini API keys found in ai.json.enc; skipping vector generation.');
  process.exit(0);
}

// We will generate one embedding per topic file here.
const embeddings: number[][] = [];
const chunkIds: string[] = [];
const embedddingStats: EmbeddingResult['stats'][] = [];

for (const [slug, content] of entries) {
  process.stdout.write(`Embedding ${slug}... `);

  // Use the list of Gemini keys to generate an embedding for this topic.
  // generateEmbedding will try the keys sequentially, rotating on retryable failures.
  // We request a fixed 768-dimensional embedding vector here.
  const result = await generateEmbedding(content, {
    fetch,
    apiKeys: keyPool,
    model: VECTOR_MODEL,
    vectorDimension: VECTOR_DIM,
  });

  if (!result || result.vector.length === 0) {
    console.warn('failed');
    continue;
  }

  const { vector, stats } = result;
  embedddingStats.push(stats);
  // Normalize the vector to unit length before storing it.
  // This makes cosine similarity calculation at query time simpler.
  const normalized = normalizeVector(vector);
  embeddings.push(normalized);
  chunkIds.push(`${slug}#0`);
  console.log('ok');
}

if (embeddings.length > 0) {
  // Write the embedding index as a TypeScript module.
  // This file exports the vector dimension, count, base64-encoded payload,
  // and chunk IDs. The Cloudflare Worker imports it at build time so the
  // vector search data is available without runtime network or file access.
  const vectorModule = buildVectorsModule(
    embeddings,
    chunkIds,
    embeddings[0].length,
    VECTOR_MODEL,
  );
  await writeFile(vectorsPath, vectorModule, 'utf-8');
  const statsSummary = summarizeEmbeddingStats(embedddingStats);

  if (statsSummary.length > 0) {
    console.log('Embedding key usage summary:');
    const headers = ['KEY', 'OWNER', 'TRY', 'OK', 'FAIL'];
    const rows = statsSummary.map((entry) => {
      const maskedKey = maskApiKey(entry.key);
      return [maskedKey, entry.owner, String(entry.nbTry), String(entry.nbSuccess), String(entry.nbFail)];
    });

    const colWidths = headers.map((header, index) =>
      Math.max(header.length, ...rows.map((row) => row[index].length)),
    );

    console.log(headers.map((header, index) => header.padEnd(colWidths[index])).join(' | '));
    console.log(colWidths.map((width) => '-'.repeat(width)).join('-+-'));

    for (const row of rows) {
      console.log(
        row.map((cell, index) =>
          index < 2 ? cell.padEnd(colWidths[index]) : cell.padStart(colWidths[index]),
        ).join(' | '),
      );
    }
  }

  console.log(`✓ Generated ${embeddings.length} embeddings → src/search/vectors.ts`);
} else {
  console.warn('⚠ No embeddings generated; skipping src/search/vectors.ts creation.');
}
